// Bumped with each notable alpha update — shown in the landing footer.
export const VERSION = 'v0.9.4-alpha';
export const UPDATED = '6 September 2026';

export const PATCH_NOTES = [
  'v0.9.4 — You can now SEE the ritual circle. The moment a Rite of the Nexus begins, the 12 squares ringing the Nexus light up in the ritualist’s colour with a slow, soft glow — the ground they have to hold, and that everyone else has to break into. It fades away when the Rite ends or is broken.',
  'v0.9.3 — BALANCE. Four changes from playtesting. (1) The attacker no longer gets an edge: ties are RE-ROLLED again rather than going to the attacker, so an even fight is a straight 50:50 and a lone Warrior is back to 50%, not 58%. (2) A Priest that survives an attack no longer flees — winning its defence repels the attacker and neither unit moves. (3) The Rite of the Nexus is much harder. It is no longer enough to hold the 2x2: the RITUAL CIRCLE, the ring of 12 squares around the Nexus (the two squares outside each side, plus the four diagonals), must ALSO be clear of enemies, both to begin the Rite and to keep it. Sixteen squares in all — friendly units may screen them, and one enemy stepping anywhere into the ring breaks it. (4) The Rite is now judged when play RETURNS to you, not at the round boundary, so an opponent who activates before you in the following round gets one final move to break it.',
  'v0.9.2 — Hover any piece and it now names itself: a small plate reads Warrior, Priest or Mage in that player\u2019s colour, so you can tell a crowded board apart at a glance. And the activation buttons are clearer: instead of one “End Activation”, you get UNDO and SUBMIT MOVE. Move to the wrong square and Undo puts the piece back and returns the die, as though the activation never began. Submit Move commits it and passes play on. One limit, so nobody gets a free re-roll: once a fight has been resolved the dice have spoken, and Undo is greyed out for the rest of that activation.',
  'v0.9.1 — NEW TURN SYSTEM. Rounds are now ALTERNATING. Every player rolls all five dice at the start of a round and nothing is discarded — all five stay on the table, and you simply never spend more than three of them. Play then goes back and forth: pick one die, move that unit, resolve its action, and pass. The exception is same-colour dice — spend two or three Warrior dice together and all those Warriors move and coordinate in a single activation before your opponent gets a go. Whatever you do not spend is ignored at the end of the round, and the starting player alternates each round.',
  'v0.9 — RULES UPDATE. MageStones now remember: once a stone has been Activated it stays Activated for the rest of the game, wherever it goes and whoever ends up holding it. Pick up an already-Activated stone and it counts straight away — no trip home. Gravestones have become a finite shared bank (4 per player, 8 in a two-player game and 16 in a four-player game) that is NEVER refilled: every Warrior death and every resurrection spends one for good, so once it empties your losses are permanent. Together those two changes give every game a natural ending. Also: ties in combat now go to the ATTACKER (no more re-rolls, and every win chance has shifted — a lone Warrior is 58%, not 50%); Bolt is indefensible, so nothing can repel it, not even a Mage; Nova costs 4 stones, kills only ENEMIES in the 8 surrounding squares and lays its four spent stones on the diagonals, still Activated and free for anyone to claim; a Priest that wins its defence may now FLEE up to its defence roll, and if it lands on a gravestone it resurrects there and then, even out of turn; only one resurrection per turn otherwise. 3-player games have been removed — MageStone is a 2- or 4-player game. The AI understands all of it, the Rule Book and tutorial teach all of it, and the engine now has an automated test suite covering every rule above.',
  'v0.8.3 — The AI Bot finally plays the MageStone game. Its Mage used to sit at home and leave the stones alone; it now goes and gets them, carries them back to activate, climbs to the d12 and d20 power tiers, and wins by MageStone about as often as by Ritual. Across measured games it activates roughly seven times as many stones as before — and it is stronger for it, not weaker.',
  'v0.8.2 — Dice fix: a die (usually the Mage die) could end up hovering above the table after a roll. Dice now always come to rest flat on the tray, never stacked or floating, and they settle sooner. The throw itself is more natural too — the dice are cast low across the tray and tumble to a stop instead of being lobbed high and drifting down.',
  'v0.8.1 — Tutorial polish, especially on phones: coach notes now dock beside the board instead of on top of it, so every unit, square and glowing target the lesson talks about stays visible while you play it. Victory notes no longer run off the screen edge, a step counter (like 12 / 46) shows your progress, Skip asks before throwing your run away, siege lessons keep the besieged base in view on desktop too, and a dozen wording fixes make every rule read right first time.',
  'v0.8 — The AI Bot got meaner. It now thinks half a second per move, plays out your best possible reply turn (including when your dice roll WELL) before committing to a line, hunts down any Mage a stone away from winning like it would a live Ritual, prices a besieged respawn as the near-elimination it is, and plans its dice keeps a whole turn deep. Verified: 30-0 sweep vs the old Medium brain, and it never plays weaker than the previous champion. No cheating — it sees only what you see.',
  'v0.7.5 — Cleaner main menu: the castle towers, corner scrollwork and gold frame are gone from the cover — just the green fade around the MageStone emblem and wordmark now. Mobile menu re-checked: every button sits clear of the art on phones and desktops.',
  'v0.7.4 — New main-menu artwork: the gold MageStone emblem cover now fronts the game, tuned for desktop and phones (the emblem and wordmark stay in frame at any screen shape). Same menu, same controls, grander door.',
  'v0.7.3 — Siege and Conquest are now hands-on in the tutorial: you lay the siege yourself, switch sides to break it as Blue (freeing the respawn queue the instant the intruder falls), then seal Blue’s base and land the finishing blow for a Conquest victory. Every scene of the tutorial is now played, not watched.',
  'v0.7.2 — Tutorial guardrails: during each hands-on step only the taught move works. Wrong units, wrong squares and wrong buttons simply don’t respond, so you can’t derail the lesson — walk the Priest only onto the gravestone, launch only the Triple Attack, step the Mage only onto your base.',
  'v0.7.1 — Real orchestral soundtrack: a cinematic fantasy theme on the main menu and a calm magical score during matches (licensed from the Ultimate Game Music Collection), replacing the old synthesised tune. Crossfades between screens; the music toggle works as before.',
  'v0.7 — The tutorial is now HANDS-ON: you roll, discard, move, fight, resurrect, collect, cast Bolt & Nova and win by MageStone and Ritual yourself, coached step by step. Dice tags are now M · P · W1 W2 W3. Feedback submissions are readable by everyone. Ranked is paused during the playtest.',
  'v0.6.5 — The dice tray now names each die (Mage · Priest · Warrior, in their colours). One AI strength: Easy and Medium are gone — every bot is the full AI Bot brain, with more human pacing (it visibly weighs its big attacks) and varied play from game to game.',
  'v0.6.4 — Undo button: discarded the wrong die? Take it back — available until any unit moves or acts that turn. Works in online games too.',
  'v0.6.3 — Dice now land showing their actual result first time: no more settling on one number and flicking to another, and they rest where they fall instead of snapping into a row. All gold buttons cleaned up to a flat style with crisp borders.',
  'v0.6.2 — Tutorial rebuilt around what confused playtesters: sieges now play out on the board (respawns visibly blocked, then freed when the besieger falls), a failed coordinated attack + resurrection demo, Bolt range highlighting, Nova friendly-fire and the stones scattering. New rule: if the home square is taken, a respawning Mage/Priest appears on the closest free base square. Rule Book corrected; attack buttons cleaned up.',
  'v0.6.1 — Hard AI plays like a master: it now reads 5–10 plays ahead, simulating your whole reply turn before it commits, spots wins and blocks yours turns in advance. Beats the previous Hard bot 2 games to 1.',
  'v0.6 — AI bots improved intelligence: the hard bot now plans turns ahead and uses Mage sorcery (Bolt & Nova). Plus layout fixes across desktop and mobile.',
  'v0.5 — Ranked matchmaking + ELO ladder (five tiers), guided tutorial with all three victories played out, in-game Rule Book, guest play with invite links, alpha feedback form.',
  'v0.4 — Guided tutorial mode, action-bar attacks with win odds, online usernames, loading screen, landscape prompt.',
  'v0.3 — Real physics combat dice (d6/d12/d20), leaderboard, victory methods named, alpha + copyright notices.',
  'v0.2 — Online multiplayer with rooms, AI bots (easy/medium/hard), mobile layout, fullscreen/PWA.',
  'v0.1 — Core rules engine, 3D board and chamber, hotseat play.',
];

export const KNOWN_ISSUES = [
  'All artwork is placeholders for the open alpha and is subject to change.',
  'The free-tier server sleeps when idle — the first online action can take ~30 seconds while it wakes.',
  'If the online host disconnects mid-game, bots idle until the host returns.',
  'iPhone Safari cannot enter fullscreen from the button — use Add to Home Screen instead.',
  'Choosing which Warrior falls in a lost coordinated attack is automatic for now.',
];
